// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all procedure arg schemas
import * as AnalyzeCallProcedure from "../analyze_call_procedure";
import * as ApproveHoldProcedure from "../approve_hold_procedure";
import * as RefreshAccountProcedure from "../refresh_account_procedure";
import * as RequestTransferProcedure from "../request_transfer_procedure";

export type AnalyzeCallArgs = __Infer<typeof AnalyzeCallProcedure.params>;
export type AnalyzeCallResult = __Infer<typeof AnalyzeCallProcedure.returnType>;
export type ApproveHoldArgs = __Infer<typeof ApproveHoldProcedure.params>;
export type ApproveHoldResult = __Infer<typeof ApproveHoldProcedure.returnType>;
export type RefreshAccountArgs = __Infer<typeof RefreshAccountProcedure.params>;
export type RefreshAccountResult = __Infer<typeof RefreshAccountProcedure.returnType>;
export type RequestTransferArgs = __Infer<typeof RequestTransferProcedure.params>;
export type RequestTransferResult = __Infer<typeof RequestTransferProcedure.returnType>;

