// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AddTranscriptReducer from "../add_transcript_reducer";
import ArmGuardReducer from "../arm_guard_reducer";
import EndCallReducer from "../end_call_reducer";
import RejectHoldReducer from "../reject_hold_reducer";
import SeedPayeeReducer from "../seed_payee_reducer";
import SetConfigReducer from "../set_config_reducer";
import SetSecretReducer from "../set_secret_reducer";
import StartCallReducer from "../start_call_reducer";

export type AddTranscriptParams = __Infer<typeof AddTranscriptReducer>;
export type ArmGuardParams = __Infer<typeof ArmGuardReducer>;
export type EndCallParams = __Infer<typeof EndCallReducer>;
export type RejectHoldParams = __Infer<typeof RejectHoldReducer>;
export type SeedPayeeParams = __Infer<typeof SeedPayeeReducer>;
export type SetConfigParams = __Infer<typeof SetConfigReducer>;
export type SetSecretParams = __Infer<typeof SetSecretReducer>;
export type StartCallParams = __Infer<typeof StartCallReducer>;

