/**
 * Transfer execution worker.
 *
 * Subscribes to approved and held transfer_intents in SpacetimeDB.
 * Approved intents are sent to Nessie, then marked completed or failed.
 * Held intents stay cached and expire after their hold time without Nessie.
 *
 * Prerequisites:
 *   spacetime start
 *   npm run spacetime:publish:local
 *   npm run spacetime:generate
 *   npm run worker:dev
 */

import { refreshAccount, type ActivityRow, type PayeeRow, type SnapshotRow } from './account.js';
import { dueHoldIds } from './expire.js';
import { executeNessieTransfer } from './nessie-client.js';

// Generated by: npm run spacetime:generate
// eslint-disable-next-line import/no-unresolved
import { DbConnection, tables } from './module_bindings/index.js';

const SPACETIME_URI =
  process.env.SPACETIME_URI ?? 'ws://127.0.0.1:3000';
const DATABASE_NAME = process.env.SPACETIME_DATABASE ?? 'scamshield-dev';
const TOKEN = process.env.SPACETIME_TOKEN;

const inFlight = new Set<string>();

type HeldRow = {
  id: bigint;
  status: { tag: string };
  expiresAtMs: number | null;
};

const heldRows = new Map<bigint, HeldRow>();
let holdExpiryTimer: ReturnType<typeof setInterval> | undefined;

type TransferRow = {
  id: bigint;
  userId: string;
  amountCents: bigint;
  destinationAccount: string;
  memo?: string;
  status: { tag: string };
  expiresAt?: { toDate(): Date } | null;
};

type WorkerContext = {
  reducers: {
    completeTransfer: (args: {
      intentId: bigint;
      nessieTransferId: string;
    }) => void;
    failTransfer: (args: { intentId: bigint; reason: string }) => void;
    expireHeldTransfer: (args: { intentId: bigint }) => void;
    upsertAccountSnapshot: (args: SnapshotRow) => void;
    replaceActivity: (args: { rows: ActivityRow[] }) => void;
    upsertPayee: (args: PayeeRow) => void;
  };
};

// Generated bindings do not include expireHeldTransfer or the account reducers yet.
function asWorkerContext(conn: { reducers: object }): WorkerContext {
  return conn as unknown as WorkerContext;
}

function expiresAtToMs(expiresAt: { toDate(): Date } | null | undefined): number | null {
  if (!expiresAt) return null;
  return expiresAt.toDate().getTime();
}

function syncHeldRow(row: TransferRow) {
  if (row.status.tag !== 'Held') {
    heldRows.delete(row.id);
    return;
  }
  heldRows.set(row.id, {
    id: row.id,
    status: row.status,
    expiresAtMs: expiresAtToMs(row.expiresAt),
  });
}

function expireDueHolds(ctx: WorkerContext, nowMs: number) {
  for (const intentId of dueHoldIds([...heldRows.values()], nowMs)) {
    ctx.reducers.expireHeldTransfer({ intentId });
  }
}

function startHoldExpiry(ctx: WorkerContext) {
  if (holdExpiryTimer) clearInterval(holdExpiryTimer);
  holdExpiryTimer = setInterval(() => {
    expireDueHolds(ctx, Date.now());
  }, 60_000);
}

function stopHoldExpiry() {
  if (!holdExpiryTimer) return;
  clearInterval(holdExpiryTimer);
  holdExpiryTimer = undefined;
  heldRows.clear();
}

async function handleApprovedIntent(
  ctx: WorkerContext,
  row: TransferRow
) {
  if (row.status.tag !== 'Approved') return;

  const key = row.id.toString();
  if (inFlight.has(key)) return;
  inFlight.add(key);

  console.log(
    `[worker] Executing approved transfer ${key} for user ${row.userId}: $${Number(row.amountCents) / 100}`
  );

  const result = await executeNessieTransfer({
    intentId: row.id,
    userId: row.userId,
    amountCents: row.amountCents,
    destinationAccount: row.destinationAccount,
    memo: row.memo,
  });

  if (result.ok) {
    ctx.reducers.completeTransfer({
      intentId: row.id,
      nessieTransferId: result.transferId,
    });
    console.log(`[worker] Transfer ${key} completed (${result.transferId})`);
  } else {
    ctx.reducers.failTransfer({
      intentId: row.id,
      reason: result.error,
    });
    console.error(`[worker] Transfer ${key} failed: ${result.error}`);
  }

  inFlight.delete(key);
  void refreshAccount(ctx);
}

function registerHandlers(conn: InstanceType<typeof DbConnection>) {
  conn.db.transferIntents.onInsert((ctx, row) => {
    syncHeldRow(row);
    void handleApprovedIntent(asWorkerContext(ctx), row);
  });

  conn.db.transferIntents.onUpdate((ctx, _oldRow, row) => {
    syncHeldRow(row);
    void handleApprovedIntent(asWorkerContext(ctx), row);
  });

  conn.db.transferIntents.onDelete((_ctx, row) => {
    heldRows.delete(row.id);
  });
}

function connect() {
  const builder = DbConnection.builder()
    .withUri(SPACETIME_URI)
    .withDatabaseName(DATABASE_NAME)
    .onConnect(conn => {
      console.log(`[worker] Connected to SpacetimeDB (${DATABASE_NAME})`);
      const ctx = asWorkerContext(conn);
      registerHandlers(conn);
      void refreshAccount(ctx);
      startHoldExpiry(ctx);

      conn.subscriptionBuilder().subscribe([
        tables.transferIntents.where(r => r.status.eq('Approved')),
        tables.transferIntents.where(r => r.status.eq('Held')),
      ]);
    })
    .onConnectError((_ctx, err) => {
      console.error('[worker] Connection error:', err);
    })
    .onDisconnect(() => {
      stopHoldExpiry();
      console.warn('[worker] Disconnected — retrying in 3s');
      setTimeout(connect, 3000);
    });

  if (TOKEN) {
    builder.withToken(TOKEN);
  }

  builder.build();
}

console.log('[worker] ScamShield transfer worker starting…');
connect();
