/**
 * Transfer execution worker.
 *
 * Subscribes to approved and held transfer_intents in SpacetimeDB.
 * Approved intents are sent to Nessie, then marked completed or failed.
 * Held intents stay cached and expire after their hold time without Nessie.
 *
 * Prerequisites:
 *   spacetime start
 *   npm run spacetime:publish:local
 *   npm run spacetime:generate
 *   npm run worker:dev
 */

import { createServer } from 'node:http';
import { refreshAccount } from './account.js';
import { settleApprovedIntent } from './approved-intent.js';
import { dueHoldIds } from './expire.js';

// Generated by: npm run spacetime:generate
// eslint-disable-next-line import/no-unresolved
import { DbConnection, tables } from './module_bindings/index.js';

const SPACETIME_URI =
  process.env.SPACETIME_URI ?? 'ws://127.0.0.1:3000';
const DATABASE_NAME = process.env.SPACETIME_DATABASE ?? 'watchdog-dev';
const TOKEN = process.env.SPACETIME_TOKEN;

const inFlight = new Set<string>();

type HeldRow = {
  id: bigint;
  status: { tag: string };
  expiresAtMs: number | null;
};

const heldRows = new Map<bigint, HeldRow>();
let holdExpiryTimer: ReturnType<typeof setInterval> | undefined;
let accountRefreshTimer: ReturnType<typeof setInterval> | undefined;
let refreshCtx: WorkerContext | null = null;

const ACCOUNT_REFRESH_MS = Number(process.env.NESSIE_REFRESH_MS ?? 15_000);
const REFRESH_PORT = Number(process.env.WORKER_REFRESH_PORT ?? 8788);

type TransferRow = {
  id: bigint;
  userId: string;
  amountCents: bigint;
  destinationAccount: string;
  memo?: string;
  status: { tag: string };
  expiresAt?: { toDate(): Date } | null;
};

/** Anything with the generated, typed reducers: the connection or an event context. */
type WorkerContext = { reducers: InstanceType<typeof DbConnection>['reducers'] };

function expiresAtToMs(expiresAt: { toDate(): Date } | null | undefined): number | null {
  if (!expiresAt) return null;
  return expiresAt.toDate().getTime();
}

function syncHeldRow(row: TransferRow) {
  if (row.status.tag !== 'Held') {
    heldRows.delete(row.id);
    return;
  }
  heldRows.set(row.id, {
    id: row.id,
    status: row.status,
    expiresAtMs: expiresAtToMs(row.expiresAt),
  });
}

function expireDueHolds(ctx: WorkerContext, nowMs: number) {
  for (const intentId of dueHoldIds([...heldRows.values()], nowMs)) {
    ctx.reducers.expireHeldTransfer({ intentId });
  }
}

function startHoldExpiry(ctx: WorkerContext) {
  if (holdExpiryTimer) clearInterval(holdExpiryTimer);
  holdExpiryTimer = setInterval(() => {
    expireDueHolds(ctx, Date.now());
  }, 60_000);
}

function startAccountRefresh(ctx: WorkerContext) {
  refreshCtx = ctx;
  if (accountRefreshTimer) clearInterval(accountRefreshTimer);
  accountRefreshTimer = setInterval(() => {
    void refreshAccount(ctx);
  }, ACCOUNT_REFRESH_MS);
}

function stopHoldExpiry() {
  if (holdExpiryTimer) {
    clearInterval(holdExpiryTimer);
    holdExpiryTimer = undefined;
  }
  if (accountRefreshTimer) {
    clearInterval(accountRefreshTimer);
    accountRefreshTimer = undefined;
  }
  refreshCtx = null;
  heldRows.clear();
}

function startRefreshEndpoint() {
  const server = createServer((req, res) => {
    if (req.method === 'POST' && (req.url === '/refresh' || req.url === '/refresh/')) {
      if (!refreshCtx) {
        res.writeHead(503, { 'content-type': 'text/plain' });
        res.end('worker is not connected');
        return;
      }
      void refreshAccount(refreshCtx).then(
        () => {
          res.writeHead(204);
          res.end();
        },
        (err: unknown) => {
          res.writeHead(500, { 'content-type': 'text/plain' });
          res.end(err instanceof Error ? err.message : String(err));
        }
      );
      return;
    }
    res.writeHead(404);
    res.end();
  });
  server.listen(REFRESH_PORT, '127.0.0.1', () => {
    console.log(`[worker] Refresh endpoint http://127.0.0.1:${REFRESH_PORT}/refresh`);
  });
  server.on('error', (err) => {
    console.error(`[worker] Refresh endpoint failed: ${err instanceof Error ? err.message : String(err)}`);
  });
}

async function handleApprovedIntent(
  ctx: WorkerContext,
  row: TransferRow
) {
  const outcome = await settleApprovedIntent(ctx.reducers, row, inFlight);
  if (outcome === 'completed' || outcome === 'failed') void refreshAccount(ctx);
}

function registerHandlers(conn: InstanceType<typeof DbConnection>) {
  conn.db.transferIntents.onInsert((ctx, row) => {
    syncHeldRow(row);
    void handleApprovedIntent(ctx, row);
  });

  conn.db.transferIntents.onUpdate((ctx, _oldRow, row) => {
    syncHeldRow(row);
    void handleApprovedIntent(ctx, row);
  });

  conn.db.transferIntents.onDelete((_ctx, row) => {
    heldRows.delete(row.id);
  });
}

function connect() {
  const builder = DbConnection.builder()
    .withUri(SPACETIME_URI)
    .withDatabaseName(DATABASE_NAME)
    .onConnect(conn => {
      console.log(`[worker] Connected to SpacetimeDB (${DATABASE_NAME})`);
      const ctx = conn;
      registerHandlers(conn);
      void refreshAccount(ctx);
      startHoldExpiry(ctx);
      startAccountRefresh(ctx);

      // The 2.10 query builder cannot compare the TransferIntentStatus enum column
      // with a literal, so subscribe to the table. syncHeldRow and
      // settleApprovedIntent only act on Held / Approved rows.
      conn.subscriptionBuilder().subscribe([tables.transferIntents]);
    })
    .onConnectError((_ctx, err) => {
      console.error('[worker] Connection error:', err);
    })
    .onDisconnect(() => {
      stopHoldExpiry();
      console.warn('[worker] Disconnected — retrying in 3s');
      setTimeout(connect, 3000);
    });

  if (TOKEN) {
    builder.withToken(TOKEN);
  }

  builder.build();
}

console.log('[worker] Watchdog transfer worker starting…');
startRefreshEndpoint();
connect();
