// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  CallSessionStatus,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  userId: __t.string().name("user_id"),
  startedAt: __t.timestamp().name("started_at"),
  endedAt: __t.option(__t.timestamp()).name("ended_at"),
  riskScore: __t.u8().name("risk_score"),
  get status() {
    return CallSessionStatus;
  },
  callerNumber: __t.option(__t.string()).name("caller_number"),
  twilioCallSid: __t.option(__t.string()).name("twilio_call_sid"),
});
