// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  sessionId: __t.u64().name("session_id"),
  userId: __t.string().name("user_id"),
  occurredAt: __t.timestamp().name("occurred_at"),
  signalType: __t.string().name("signal_type"),
  transcriptExcerpt: __t.string().name("transcript_excerpt"),
  riskScoreAfter: __t.u8().name("risk_score_after"),
  warningMessage: __t.option(__t.string()).name("warning_message"),
});
