// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  TransferIntentStatus,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  userId: __t.string().name("user_id"),
  sessionId: __t.option(__t.u64()).name("session_id"),
  requestedAt: __t.timestamp().name("requested_at"),
  amountCents: __t.u64().name("amount_cents"),
  destinationAccount: __t.string().name("destination_account"),
  memo: __t.option(__t.string()),
  get status() {
    return TransferIntentStatus;
  },
  holdReason: __t.option(__t.string()).name("hold_reason"),
  riskScoreAtDecision: __t.u8().name("risk_score_at_decision"),
  nessieTransferId: __t.option(__t.string()).name("nessie_transfer_id"),
  completedAt: __t.option(__t.timestamp()).name("completed_at"),
  expiresAt: __t.option(__t.timestamp()).name("expires_at"),
});
