// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const AccountSnapshot = __t.object("AccountSnapshot", {
  id: __t.u8(),
  name: __t.string(),
  nickname: __t.string(),
  last4: __t.string(),
  balance: __t.f64(),
  updatedAt: __t.timestamp(),
});
export type AccountSnapshot = __Infer<typeof AccountSnapshot>;

export const Activity = __t.object("Activity", {
  id: __t.string(),
  kind: __t.string(),
  date: __t.string(),
  description: __t.string(),
  amount: __t.f64(),
  sortIndex: __t.u32(),
});
export type Activity = __Infer<typeof Activity>;

export const ActivityRow = __t.object("ActivityRow", {
  id: __t.string(),
  kind: __t.string(),
  date: __t.string(),
  description: __t.string(),
  amount: __t.f64(),
  sortIndex: __t.u32(),
});
export type ActivityRow = __Infer<typeof ActivityRow>;

// The tagged union or sum type for the algebraic type `CallSessionStatus`.
export const CallSessionStatus = __t.enum("CallSessionStatus", {
  Active: __t.unit(),
  Ended: __t.unit(),
});
export type CallSessionStatus = __Infer<typeof CallSessionStatus>;

export const CallSessions = __t.object("CallSessions", {
  id: __t.u64(),
  userId: __t.string(),
  startedAt: __t.timestamp(),
  endedAt: __t.option(__t.timestamp()),
  riskScore: __t.u8(),
  get status() {
    return CallSessionStatus;
  },
  callerNumber: __t.option(__t.string()),
  twilioCallSid: __t.option(__t.string()),
});
export type CallSessions = __Infer<typeof CallSessions>;

export const Config = __t.object("Config", {
  id: __t.u8(),
  riskHoldThreshold: __t.u8(),
});
export type Config = __Infer<typeof Config>;

export const Payees = __t.object("Payees", {
  name: __t.string(),
  nessieAccountId: __t.string(),
  trusted: __t.bool(),
});
export type Payees = __Infer<typeof Payees>;

export const RiskEvents = __t.object("RiskEvents", {
  id: __t.u64(),
  sessionId: __t.u64(),
  userId: __t.string(),
  occurredAt: __t.timestamp(),
  signalType: __t.string(),
  transcriptExcerpt: __t.string(),
  riskScoreAfter: __t.u8(),
  warningMessage: __t.option(__t.string()),
});
export type RiskEvents = __Infer<typeof RiskEvents>;

export const TranscriptSegments = __t.object("TranscriptSegments", {
  id: __t.u64(),
  sessionId: __t.u64(),
  userId: __t.string(),
  occurredAt: __t.timestamp(),
  text: __t.string(),
  source: __t.string(),
  isFinal: __t.bool(),
});
export type TranscriptSegments = __Infer<typeof TranscriptSegments>;

// The tagged union or sum type for the algebraic type `TransferIntentStatus`.
export const TransferIntentStatus = __t.enum("TransferIntentStatus", {
  Pending: __t.unit(),
  Approved: __t.unit(),
  Held: __t.unit(),
  Completed: __t.unit(),
  Failed: __t.unit(),
  Released: __t.unit(),
  Expired: __t.unit(),
});
export type TransferIntentStatus = __Infer<typeof TransferIntentStatus>;

export const TransferIntents = __t.object("TransferIntents", {
  id: __t.u64(),
  userId: __t.string(),
  sessionId: __t.option(__t.u64()),
  requestedAt: __t.timestamp(),
  amountCents: __t.u64(),
  destinationAccount: __t.string(),
  memo: __t.option(__t.string()),
  get status() {
    return TransferIntentStatus;
  },
  holdReason: __t.option(__t.string()),
  riskScoreAtDecision: __t.u8(),
  nessieTransferId: __t.option(__t.string()),
  completedAt: __t.option(__t.timestamp()),
  expiresAt: __t.option(__t.timestamp()),
});
export type TransferIntents = __Infer<typeof TransferIntents>;

