// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const AccountSnapshot = __t.object("AccountSnapshot", {
  id: __t.u8(),
  name: __t.string(),
  nickname: __t.string(),
  last4: __t.string(),
  balance: __t.f64(),
});
export type AccountSnapshot = __Infer<typeof AccountSnapshot>;

export const Activity = __t.object("Activity", {
  id: __t.string(),
  kind: __t.string(),
  date: __t.string(),
  description: __t.string(),
  amount: __t.f64(),
  sortIndex: __t.u32(),
});
export type Activity = __Infer<typeof Activity>;

export const Alert = __t.object("Alert", {
  id: __t.u64(),
  callId: __t.u64(),
  kind: __t.string(),
  message: __t.string(),
  createdAt: __t.timestamp(),
});
export type Alert = __Infer<typeof Alert>;

export const AnalyzeResult = __t.object("AnalyzeResult", {
  ok: __t.bool(),
  score: __t.u32(),
  state: __t.string(),
  message: __t.string(),
});
export type AnalyzeResult = __Infer<typeof AnalyzeResult>;

export const Bill = __t.object("Bill", {
  id: __t.string(),
  payee: __t.string(),
  amount: __t.f64(),
  paymentDate: __t.string(),
  status: __t.string(),
});
export type Bill = __Infer<typeof Bill>;

export const Call = __t.object("Call", {
  id: __t.u64(),
  callerNumber: __t.string(),
  startedAt: __t.timestamp(),
  endedAt: __t.option(__t.timestamp()),
  score: __t.u32(),
  state: __t.string(),
});
export type Call = __Infer<typeof Call>;

export const Config = __t.object("Config", {
  id: __t.u8(),
  mock: __t.bool(),
  accountId: __t.string(),
  supportsPurchases: __t.bool(),
  supportsTransfers: __t.bool(),
});
export type Config = __Infer<typeof Config>;

export const Guard = __t.object("Guard", {
  id: __t.u8(),
  armedUntil: __t.timestamp(),
});
export type Guard = __Infer<typeof Guard>;

export const Hold = __t.object("Hold", {
  id: __t.u64(),
  payee: __t.string(),
  amount: __t.f64(),
  memo: __t.string(),
  reason: __t.string(),
  status: __t.string(),
  createdAt: __t.timestamp(),
  expiresAt: __t.timestamp(),
});
export type Hold = __Infer<typeof Hold>;

export const MockTxn = __t.object("MockTxn", {
  id: __t.u64(),
  date: __t.string(),
  description: __t.string(),
  amount: __t.f64(),
});
export type MockTxn = __Infer<typeof MockTxn>;

export const Payee = __t.object("Payee", {
  name: __t.string(),
  nessieAccountId: __t.string(),
  trusted: __t.bool(),
  timesPaid: __t.u32(),
});
export type Payee = __Infer<typeof Payee>;

export const RefreshResult = __t.object("RefreshResult", {
  ok: __t.bool(),
  message: __t.string(),
});
export type RefreshResult = __Infer<typeof RefreshResult>;

export const ReportedNumber = __t.object("ReportedNumber", {
  number: __t.string(),
  reports: __t.u32(),
});
export type ReportedNumber = __Infer<typeof ReportedNumber>;

export const Secret = __t.object("Secret", {
  name: __t.string(),
  value: __t.string(),
});
export type Secret = __Infer<typeof Secret>;

export const TacticHit = __t.object("TacticHit", {
  id: __t.u64(),
  callId: __t.u64(),
  tactic: __t.string(),
});
export type TacticHit = __Infer<typeof TacticHit>;

export const Transcript = __t.object("Transcript", {
  id: __t.u64(),
  callId: __t.u64(),
  atMs: __t.u32(),
  speaker: __t.string(),
  text: __t.string(),
  labelsJson: __t.option(__t.string()),
});
export type Transcript = __Infer<typeof Transcript>;

export const TransferResult = __t.object("TransferResult", {
  outcome: __t.string(),
  message: __t.string(),
  rule: __t.u32(),
  viaWithdrawal: __t.bool(),
});
export type TransferResult = __Infer<typeof TransferResult>;

export const Verdict = __t.object("Verdict", {
  id: __t.u64(),
  callId: __t.u64(),
  claimJson: __t.string(),
  claimTrue: __t.bool(),
  evidence: __t.string(),
});
export type Verdict = __Infer<typeof Verdict>;

